Repository gnosis/safe-react, pull requests merged in 2020-05, with the labels that each got.

#869 Rename desktop
  package.json
  public/electron.js
Labels: Reviewing

#870 Feature/desktop logs
  public/electron.js
  scripts/preload.js
Labels: Reviewing

#854 Wallet dashboard
  src/components/Header/components/ProviderDetails/UserDetails.jsx
  src/components/Header/index.jsx
  src/logic/wallets/utils/walletList.js
  yarn.lock
Labels: Reviewing

#880 Disable Analytics and Cookie Banner
  .github/workflows/release.yml
  config/webpack.config.prod.js
  package.json
  src/components/CookiesBanner/index.jsx
Labels: Reviewing

#885 Upload Artifacts when building desktop
  .github/workflows/release.yml
Labels: Reviewing

#931 Prevent github action from running
  .github/workflows/release.yml
Labels: Bug 🐛

#937 Bug: fix build directory for deployment, remove unused code
  .env.example
  .eslintignore
  .gitignore
  .prettierignore
  .travis.yml
  config/env.js
  config/old.webpack.config.dev.js
  config/old.webpack.config.prod.js
  config/old.webpack.config.test.js
  config/paths.js
  config/polyfills.js
  config/travis/deploy_pull_request.sh
  config/travis/deploy_release.sh
  public/electron.js
  scripts/build.js
  scripts/notarize.js
  scripts/preload.js
  scripts/start.js
  scripts/test.js
  yarn.lock
Labels: Bug 🐛

#935 Add Trezor support
  public/electron.js
  scripts/preload.js
  src/logic/wallets/utils/walletList.ts
  src/routes/safe/container/index.jsx
Labels: Enhancement ✨
