Repository gnosis/safe-react, pull requests merged in 2020-03, with the labels that each got.

#621 Adding Apps info to toast notification
  src/logic/notifications/notificationBuilder.js
  src/routes/safe/components/Apps/appsList.js
  src/routes/safe/components/Apps/index.jsx
  src/routes/safe/components/Apps/sendTransactions.js
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/RejectTxModal/index.jsx
  src/routes/safe/components/Transactions/TxsTable/TxType/assets/appsIcon.svg
  src/routes/safe/components/Transactions/TxsTable/TxType/index.jsx
  src/routes/safe/store/actions/createTransaction.js
  src/routes/safe/store/actions/processTransaction.js
Labels: Feature

#456 Feature: replace web3connect with onboardjs
  package.json
  src/components-v2/dataDisplay/IconText/index.js
  src/components/ConnectButton/index.jsx
  src/components/Header/index.jsx
  src/components/Root/OnboardCustom.scss
  src/components/Root/index.js
  src/components/Root/index.scss
  src/config/index.js
  src/logic/notifications/notificationTypes.js
  src/logic/wallets/getWeb3.js
  src/logic/wallets/store/actions/fetchProvider.js
  src/logic/wallets/store/actions/removeProvider.js
  src/logic/wallets/store/middlewares/providerWatcher.js
  src/logic/wallets/transactionDataCheck.js
  src/routes/safe/components/Balances/SendModal/screens/ReviewTx/index.jsx
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.jsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.jsx
  src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.jsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/OwnersColumn/index.jsx
  src/routes/safe/components/Transactions/TxsTable/TxType/index.jsx
  src/routes/safe/store/actions/createTransaction.js
  yarn.lock
Labels: Reviewing

#654 Onboard - Bugfixing and Improvements
  package.json
  src/components/ConnectButton/index.jsx
  yarn.lock
Labels: Bug

#665 Onboardjs - Get wallets by platform, fix ledger/trezor rpcUrls
  package.json
  src/components/ConnectButton/index.jsx
  src/logic/wallets/getWeb3.js
  src/logic/wallets/utils/walletList.js
  yarn.lock
Labels: Feature, Reviewing

#698 Customize the info shown in the Onboardjs modal
  package.json
  src/components/ConnectButton/index.jsx
  yarn.lock
Labels: Enhancement ✨, Reviewing

#703 Fix safe creation from walletConnect
  src/routes/opening/index.jsx
Labels: Bug 🐛
