Repository gnosis/safe-react, pull requests merged in 2020-08, with the labels that each got.

#1187 CLA assistant
  .github/workflows/cla.yml
Labels: Dev Tooling 🛠️

#1204 Add support from Pull Requests coming from Forks
  .github/workflows/cla.yml
Labels: Bug 🐛

#1205 Change CLA event
  .github/workflows/cla.yml
Labels: Bug 🐛

#1106 (Feature) Decode multiSend tx details
  src/components/Collapse/index.tsx
  src/components/CopyBtn/index.tsx
  src/components/EtherscanBtn/index.tsx
  src/components/EtherscanLink/index.tsx
  src/components/EtherscanLink/style.ts
  src/components/Table/sorting.ts
  src/logic/addressBook/model/addressBook.ts
  src/logic/addressBook/store/reducer/addressBook.ts
  src/logic/addressBook/store/reducer/types/addressBook.d.ts
  src/logic/addressBook/store/selectors/index.ts
  src/logic/contracts/methodIds.ts
  src/logic/currencyValues/api/fetchTokenCurrenciesBalances.ts
  src/logic/currencyValues/store/model/currencyValues.ts
  src/logic/currencyValues/store/reducer/currencyValues.ts
  src/logic/currencyValues/store/selectors/index.ts
  src/logic/tokens/store/actions/fetchSafeTokens.ts
  src/logic/tokens/utils/humanReadableValue.ts
  src/routes/safe/components/AddressBook/index.tsx
  src/routes/safe/components/Apps/confirmTransactions.tsx
  src/routes/safe/components/Balances/Coins/index.tsx
  src/routes/safe/components/Balances/dataFetcher.ts
  src/routes/safe/components/Settings/ManageOwners/OwnerAddressTableCell/index.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/CustomDescription.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/SettingsDescription.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/TransferDescription.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/Value.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/index.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/styles.ts
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/utils.ts
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/index.tsx
  src/routes/safe/components/Transactions/TxsTable/columns.tsx
  src/routes/safe/components/Transactions/TxsTable/index.tsx
  src/routes/safe/components/Transactions/TxsTable/test/column.test.ts
  src/routes/safe/store/actions/transactions/fetchTransactions/loadOutgoingTransactions.ts
  src/routes/safe/store/actions/transactions/utils/multiSendDecodedDetails.ts
  src/routes/safe/store/actions/transactions/utils/newTransactionHelpers.ts
  src/routes/safe/store/actions/transactions/utils/transactionHelpers.ts
  src/routes/safe/store/actions/transactions/utils/transferDetails.d.ts
  src/routes/safe/store/actions/transactions/utils/transferDetails.ts
  src/routes/safe/store/models/transaction.ts
  src/routes/safe/store/models/types/transaction.ts
  src/routes/safe/store/models/types/transactions.d.ts
  src/routes/safe/store/reducer/cancellationTransactions.ts
  src/routes/safe/store/reducer/types/safe.d.ts
  src/routes/safe/store/selectors/index.ts
  src/routes/safe/store/selectors/transactions.ts
  src/store/index.ts
  src/test/utils/transactions/transactionList.helper.ts
Labels: Feature 👑, High

#1134 (Feature) Add "Action" details in transaction list
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/CustomDescription.tsx
Labels: Feature 👑, High

#1209 Bug/safe crash when accessing from link
  src/routes/safe/store/actions/addSafeModules.ts
  src/routes/safe/store/actions/fetchSafe.ts
  src/routes/safe/store/reducer/safe.ts
Labels: Bug 🐛

#1217 Fix - Desktop CI
  .github/workflows/release.yml
Labels: Dev Tooling 🛠️

#1232 Result of "call" is cut off
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/RenderOutputParams/index.tsx
  yarn.lock
Labels: Bug 🐛

#1255 Etherscan link broken
  src/components/EtherscanLink/index.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/CustomDescription.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/Value.tsx
Labels: Bug 🐛, Medium

#1267 (Hotfix) Update Balancer Pool IPFS URL
  package.json
  src/routes/safe/components/Apps/utils.ts
Labels: High

#1283 Fix error trying to update Desktop App
  public/auto-updater/index.js
Labels: Bug 🐛, Medium

#1290 Update IDLE safe app link
  src/routes/safe/components/Apps/utils.ts
Labels: Bug 🐛
