Repository gnosis/safe-react, pull requests merged in 2020-09, with the labels that each got.

#1307 Bump new onboard.js version
  package.json
  yarn.lock
Labels: Enhancement ✨

#1322 Update Contract Data Modal
  package.json
  src/logic/wallets/transactionDataCheck/images/contractData.png
  src/logic/wallets/transactionDataCheck/index.ts
Labels: Enhancement ✨, Medium

#1313 Fix fees not showing in transaction details
  src/logic/contracts/generateBatchRequests.ts
  src/logic/safe/store/actions/transactions/fetchTransactions/loadIncomingTransactions.ts
  src/logic/safe/store/actions/transactions/utils/transactionHelpers.ts
  src/logic/safe/transactions/incomingTxHistory.ts
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/index.tsx
Labels: Bug 🐛

#1337 (Feature) Tooltip equivalent balance may be zero
  package.json
  src/assets/icons/info.svg
  src/routes/safe/components/Balances/Coins/index.tsx
  src/routes/safe/components/Balances/Coins/styles.ts
Labels: Enhancement ✨, High

#1340 (Bugfix) - #1286 Fix Sidebar position
  src/components/AppLayout/Sidebar/SafeHeader/index.tsx
  src/components/AppLayout/Sidebar/index.tsx
  src/components/AppLayout/index.tsx
  src/components/List/index.tsx
Labels: Bug 🐛, Medium

#1365 (Bugfix) - #925 [Contract Interaction] UI Glitch
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/style.ts
Labels: Bug 🐛

#1378 Not able to connect with Opera Touch
  package.json
  yarn.lock
Labels: Bug 🐛, Medium

#1372 ENS names not working properly
  src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
Labels: Bug 🐛, Medium

#1387 (Fix) Recipient address used as name as well
  src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
Labels: High

#1375 (Fix) (development) Missing collectibles and Safe version
  src/logic/safe/store/actions/fetchSafe.ts
  src/logic/safe/store/reducer/safe.ts
Labels: Bug 🐛

#1405 Change wording when trying to add an incompatible Safe address
  src/routes/load/components/DetailsForm/index.tsx
Labels: Enhancement ✨
