Repository gnosis/safe-react, pull requests merged in 2020-07, with the labels that each got.

#1086 Prevent showing enable data modal
  src/logic/wallets/transactionDataCheck.ts
  src/routes/open/container/Open.tsx
  src/routes/safe/store/actions/createTransaction.ts
  src/routes/safe/store/actions/processTransaction.ts
Labels: Enhancement ✨, Medium

#1081 sapp iframe size
  src/components/Footer/index.tsx
  src/components/ListContentLayout/Layout.ts
  src/routes/safe/components/Apps/index.tsx
  yarn.lock
Labels: WIP

#1064 Address Book Suggestions
  src/components/forms/validator.ts
  src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/style.ts
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/EthAddressInput/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/SendCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/index.tsx
Labels: Enhancement ✨, Medium

#1101 Allow to re-pick a contract address
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/EthAddressInput/index.tsx
Labels: Bug 🐛, Medium

#1119 Connected wallet enhancements
  src/components/Header/components/Provider.tsx
  src/components/Header/components/ProviderInfo/ProviderAccessible.tsx
  src/components/Header/components/WalletIcon/icons/icon-authereum.png
  src/components/Header/components/WalletIcon/icons/icon-coinbase.svg
  src/components/Header/components/WalletIcon/icons/icon-dapper.png
  src/components/Header/components/WalletIcon/icons/icon-fortmatic.svg
  src/components/Header/components/WalletIcon/icons/icon-ledger.svg
  src/components/Header/components/WalletIcon/icons/icon-metamask.png
  src/components/Header/components/WalletIcon/icons/icon-opera-touch.png
  src/components/Header/components/WalletIcon/icons/icon-opera.png
  src/components/Header/components/WalletIcon/icons/icon-portis.svg
  src/components/Header/components/WalletIcon/icons/icon-torus.svg
  src/components/Header/components/WalletIcon/icons/icon-trezor.svg
  src/components/Header/components/WalletIcon/icons/icon-trust.svg
  src/components/Header/components/WalletIcon/icons/icon-unilogin.svg
  src/components/Header/components/WalletIcon/icons/icon-wallet-connect.svg
  src/components/Header/components/WalletIcon/icons/index.ts
  src/components/Header/components/WalletIcon/index.tsx
  src/components/Header/index.tsx
  src/logic/wallets/getWeb3.ts
Labels: Feature 👑, Medium

#1150 Fix desktop build
  package.json
  public/build/safe.png
Labels: Bug 🐛, High

#1161 (Fix) Prevent accessing `contentWindow` if `iframe` is `null`
  src/routes/safe/components/Apps/index.tsx
Labels: Bug 🐛, High

#1160 Fix: Standardized modal alignment settings
  src/routes/safe/components/AddressBook/CreateEditEntryModal/style.ts
  src/routes/safe/components/AddressBook/DeleteEntryModal/style.ts
  src/routes/safe/components/Balances/SendModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/style.ts
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.tsx
Labels: Bug 🐛

#1108 Tech Debt: Validator Type definitions
  .eslintrc.js
  .prettierignore
  package.json
  src/components/forms/validator.test.ts
  src/components/forms/validator.ts
  src/logic/contractInteraction/sources/EtherscanService.ts
  src/logic/contracts/historicProxyCode.ts
  src/logic/contracts/safeContracts.ts
  src/logic/wallets/ethAddresses.ts
  src/routes/open/container/Open.tsx
  src/routes/safe/components/AddressBook/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/EthAddressInput/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/SendCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
  src/routes/safe/components/Balances/Tokens/screens/AddCustomAsset/validators.ts
  src/routes/safe/components/Balances/Tokens/screens/AddCustomToken/validators.ts
  src/routes/safe/components/Layout/Tabs/index.tsx
  src/routes/safe/components/Layout/index.tsx
  src/routes/safe/container/selector.ts
  src/routes/safe/store/middleware/notificationsMiddleware.ts
  src/routes/safe/store/selectors/index.ts
  src/store/index.ts
  src/test/builder/safe.dom.utils.tsx
  src/test/safe.dom.create.tsx
  yarn.lock
Labels: Tech-debt 🚧

#1159 Fix CI on github action desktop build
  config-overrides.js
Labels: Bug 🐛

#1163 Fix Wrong Wallet Network Label
  src/components/Header/components/NetworkLabel.tsx
  src/components/Header/components/ProviderInfo/ProviderAccessible.tsx
  src/components/Header/index.tsx
Labels: Bug 🐛, Medium

#1127 Fix - Owners list error
  src/logic/addressBook/store/selectors/index.ts
  src/logic/addressBook/utils/index.ts
Labels: Bug 🐛, Medium

#1142 Trim spaces from AddressInput
  package.json
  src/components/forms/AddressInput/index.tsx
  src/components/forms/Field/DebounceValidationField.tsx
  src/components/forms/validator.ts
  src/routes/load/components/DetailsForm/index.tsx
  src/routes/open/components/SafeOwnersConfirmationsForm/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
  src/routes/safe/components/Balances/Tokens/screens/AddCustomAsset/index.tsx
  src/routes/safe/components/Balances/Tokens/screens/AddCustomToken/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.tsx
  src/utils/strings.ts
  yarn.lock
Labels: Bug 🐛

#1151 (Feature) [Spending Limit] Settings tab
  src/routes/safe/components/Settings/SpendingLimit/assets/asset-amount.svg
  src/routes/safe/components/Settings/SpendingLimit/assets/beneficiary.svg
  src/routes/safe/components/Settings/SpendingLimit/assets/time.svg
  src/routes/safe/components/Settings/SpendingLimit/index.tsx
  src/routes/safe/components/Settings/SpendingLimit/style.ts
  src/routes/safe/components/Settings/index.tsx
Labels: Feature 👑, Medium

#1021 Fix: debounce fetch apps
  package.json
  src/routes/safe/components/Apps/AddAppForm.tsx
  src/routes/safe/components/Apps/AddAppForm/AppAgreement.tsx
  src/routes/safe/components/Apps/AddAppForm/AppUrl.tsx
  src/routes/safe/components/Apps/AddAppForm/SubmitButtonStatus.tsx
  src/routes/safe/components/Apps/AddAppForm/index.tsx
  src/routes/safe/components/Apps/ManageApps.tsx
  src/routes/safe/components/Apps/index.tsx
  src/routes/safe/components/Apps/types.d.ts
  src/routes/safe/components/Apps/utils.ts
  src/routes/safe/components/Transactions/TxsTable/TxType/index.tsx
  src/routes/safe/container/hooks/useDebounce.tsx
  yarn.lock
Labels: Bug 🐛, Medium
