Repository gnosis/safe-react, pull requests merged in 2020-10, with the labels that each got.

#1395 Desktop app - Detect port and change it if needed
  package.json
  public/electron.js
Labels: Enhancement ✨, Medium

#1458 Xdai deploy test
  .travis.yml
  src/config/networks/xdai.ts
Labels: do-not-merge

#1451 (Bugfix) Set min height to ListContentLayout wrapper #1447
  src/components/ListContentLayout/Layout.ts
  src/routes/safe/components/Apps/index.tsx
Labels: Bug 🐛

#1444 [xDai] Parametrize Native Coin
  src/components/AddressInfo/index.tsx
  src/components/AppLayout/Sidebar/SafeHeader/index.tsx
  src/logic/safe/store/actions/transactions/fetchTransactions/loadIncomingTransactions.ts
  src/logic/safe/store/actions/transactions/utils/transactionHelpers.ts
  src/logic/tokens/utils/__tests__/tokenHelpers.test.ts
  src/logic/tokens/utils/humanReadableValue.ts
  src/logic/tokens/utils/tokenHelpers.ts
  src/routes/open/components/ReviewInformation/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
  src/routes/safe/components/Balances/Tokens/screens/AssetsList/AssetRow.tsx
  src/routes/safe/components/Balances/Tokens/screens/TokenList/TokenRow.tsx
  src/routes/safe/components/Balances/dataFetcher.ts
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/ApproveTxModal/index.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/RejectTxModal/index.tsx
Labels: Feature 👑, High

#1442 Feature #1440: Handle transactions with set safeTxGas from Safe Apps
  .travis.yml
  package.json
  src/assets/icons/alert.svg
  src/assets/icons/check_bg.svg
  src/assets/icons/error.svg
  src/assets/icons/info.svg
  src/assets/icons/info_red.svg
  src/components/App/assets/info.svg
  src/components/App/index.tsx
  src/logic/safe/store/actions/createTransaction.ts
  src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx
  src/routes/safe/components/Apps/components/GasEstimationInfo.tsx
  src/routes/safe/components/Apps/hooks/useIframeMessageHandler.ts
  src/routes/safe/components/Apps/index.tsx
  src/routes/safe/components/Balances/Coins/index.tsx
  yarn.lock
Labels: Safe Apps

#1504 Enable/Disable wallets by configuration flag
  src/config/index.ts
  src/config/networks/network.d.ts
  src/config/networks/xdai.ts
  src/logic/wallets/utils/walletList.ts
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/index.tsx
Labels: Feature 👑, Medium

#1517 Update calculateGasPrice to fetch from config
  src/config/index.ts
  src/config/networks/local.ts
  src/config/networks/mainnet.ts
  src/config/networks/network.d.ts
  src/config/networks/rinkeby.ts
  src/logic/safe/api/estimateTxGas.ts
  src/logic/safe/api/index.ts
  src/logic/safe/store/actions/createTransaction.ts
  src/logic/safe/transactions/gas.ts
  src/logic/safe/transactions/gasNew.ts
  src/logic/safe/transactions/index.ts
  src/logic/wallets/ethTransactions.ts
  src/routes/safe/components/Apps/components/ConfirmTransactionModal.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewTx/index.tsx
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ThresholdSettings/ChangeThreshold/index.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/ApproveTxModal/index.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/RejectTxModal/index.tsx
Labels: Bug 🐛, High

#1419 Collectibles List - Manage list when no collectibles
  src/routes/safe/components/Balances/Tokens/screens/AssetsList/index.tsx
Labels: Bug 🐛

#1549 EWC/Volta - Disable not working wallets
  src/config/networks/energy_web_chain.ts
  src/config/networks/volta.ts
Labels: Bug 🐛, High
