Repository gnosis/safe-react, pull requests merged in 2020-06, with the labels that each got.

#967 Fix Ledger issues on Desktop App
  package.json
  public/electron.js
  scripts/notarize.js
  src/components/ConnectButton/index.tsx
  yarn.lock
Labels: Bug 🐛

#979 Update desktop logo
  public/build/icon.icns
  public/build/icon.ico
  public/build/safe.png
Labels: Enhancement ✨

#997 Update Desktop App dialog
  dev-app-update.yml
  package.json
  public/auto-updater/index.js
  yarn.lock
Labels: Feature 👑

#992 Add fix for Trezor on Windows
  public/electron.js
  src/routes/opening/components/Footer.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/index.tsx
  src/routes/safe/store/actions/transactions/utils/transactionHelpers.ts
Labels: Bug 🐛

#995 (Refactor) Update `dataDecoded` structure
  src/logic/contracts/methodIds.ts
  src/logic/currencyValues/store/actions/fetchCurrencyValues.ts
  src/logic/currencyValues/store/utils/currencyValuesStorage.ts
  src/logic/safe/transactions/send.ts
  src/logic/wallets/store/model/provider.ts
  src/routes/opening/components/Footer.tsx
  src/routes/safe/components/Apps/AddAppForm.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/index.tsx
  src/routes/safe/components/Layout/index.tsx
  src/routes/safe/components/Transactions/TxsTable/ExpandedTx/TxDescription/utils.ts
  src/routes/safe/store/actions/createTransaction.ts
  src/routes/safe/store/actions/processTransaction.ts
  src/routes/safe/store/actions/transactions/fetchTransactions/loadOutgoingTransactions.ts
  src/routes/safe/store/actions/transactions/utils/transactionHelpers.ts
  src/routes/safe/store/models/safe.ts
  src/routes/safe/store/models/transaction.ts
  src/routes/safe/store/models/types/transaction.ts
  src/routes/safe/store/reducer/safe.ts
  src/test/builder/safe.redux.builder.ts
  src/test/utils/safeHelper.ts
Labels: High

#1072 Fix: Sapp confirmTXs modal width.
  src/components/TextBox/index.tsx
  src/routes/safe/components/Apps/confirmTransactions.tsx
Labels: Bug 🐛

#1049 Update onboardjs version
  package.json
  yarn.lock
Labels: Enhancement ✨, Medium
