Repository gnosis/safe-react, pull requests merged in 2020-02, with the labels that each got.

#575 Fix web3connect version
  package.json
  yarn.lock
Labels: Bug

#582 (Hotfix) Safe Upgrade is not working
  src/routes/safe/store/actions/createTransaction.js
Labels: Bug, High

#576 (feature) Adding origin for Apps Transactions
  src/logic/safe/transactions/send.js
  src/logic/safe/transactions/txHistory.js
  src/routes/safe/components/Apps/index.jsx
  src/routes/safe/components/Apps/sendTransactions.js
  src/routes/safe/store/actions/__tests__/utils.test.js
  src/routes/safe/store/actions/createTransaction.js
  src/routes/safe/store/actions/processTransaction.js
  src/routes/safe/store/actions/utils.js
Labels: Bug, Feature
