Repository gnosis/safe-react, pull requests merged in 2021-05, with the labels that each got.

#2210 Spending limit UI corrections
  src/logic/notifications/notificationTypes.ts
  src/routes/safe/components/Balances/SendModal/screens/SendFunds/SpendingLimitRow.tsx
  src/routes/safe/components/Settings/SpendingLimit/FormFields/Beneficiary.tsx
  src/routes/safe/components/Settings/SpendingLimit/InfoDisplay/AddressInfo.tsx
  src/routes/safe/components/Settings/SpendingLimit/LimitsTable/index.tsx
  src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Create.tsx
  src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
  src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/index.tsx
  src/routes/safe/components/Settings/SpendingLimit/RemoveLimitModal.tsx
  src/routes/safe/components/Settings/SpendingLimit/index.tsx
  src/routes/safe/components/Settings/index.tsx
  src/routes/safe/components/Transactions/TxList/SpendingLimitDetails.tsx
Labels: Bug 🐛

#2255 Bugfix - Add Recipient name on Send Fund's second step modal
  src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
Labels: Bug 🐛

#2278 [Address Book] - Add Import/Export Buttons
  package.json
  src/routes/safe/components/AddressBook/index.tsx
  yarn.lock
Labels: Feature 👑

#2223 Send modal styles
  src/routes/safe/components/Balances/SendModal/screens/ChooseTxType/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ChooseTxType/style.ts
Labels: Bug 🐛, Minor

#2244 Bugfix - Back button resets fields on Owner modification modals
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/OwnerForm/index.tsx
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/ThresholdForm/index.tsx
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/ThresholdForm/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.tsx
Labels: Bug 🐛

#2279 Bug: Add custom app feature works weird or doesn't work
  src/routes/safe/components/Apps/components/AddAppForm/AppUrl.tsx
  src/routes/safe/components/Apps/components/AddAppForm/index.tsx
Labels: Bug 🐛

#2284 [Address Book V2] - Export address book
  package.json
  src/components/Modal/index.tsx
  src/logic/notifications/notificationBuilder.tsx
  src/logic/notifications/notificationTypes.ts
  src/logic/safe/transactions/notifiedTransactions.ts
  src/routes/safe/components/AddressBook/ExportEntriesModal/assets/error.svg
  src/routes/safe/components/AddressBook/ExportEntriesModal/assets/success.svg
  src/routes/safe/components/AddressBook/ExportEntriesModal/assets/wait.svg
  src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
  src/routes/safe/components/AddressBook/index.tsx
  yarn.lock
Labels: Feature 👑

#2285 Fix call response in contract interaction
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/RenderOutputParams/index.tsx
Labels: Bug 🐛

#2310 Bugfix - Safes added via URL not stored when changing name
  src/logic/safe/store/middleware/safeStorage.ts
  src/logic/safe/store/reducer/safe.ts
  src/routes/load/components/ReviewInformation/index.tsx
  src/routes/load/container/Load.tsx
  src/routes/safe/components/Settings/SafeDetails/index.tsx
  src/routes/safe/components/Settings/index.tsx
Labels: Bug 🐛

#2309 Tx decoded data: fix addresses array
  src/routes/safe/components/Transactions/TxList/MethodValue.tsx
Labels: Bug 🐛

#2345 [Address Book v2] Fix AB v2 migration
  src/logic/addressBook/utils/index.ts
  src/logic/addressBook/utils/v2-migration.ts
  src/logic/exceptions/registry.ts
  src/logic/safe/store/actions/loadSafesFromStorage.ts
  src/logic/safe/utils/safeStorage.ts
  src/store/index.ts
Labels: epic-address-book

#2325 Export - Add loading state when click on download button
  src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
Labels: Enhancement ✨
