Repository gnosis/safe-react, pull requests merged in 2021-04, with the labels that each got.

#2054 (Feature) - v3 Decoded Tx - Generic Modal
  src/components/App/index.tsx
  src/components/Modal/index.stories.tsx
  src/components/Modal/index.tsx
  src/routes/safe/components/AddressBook/CreateEditEntryModal/index.tsx
  src/routes/safe/components/AddressBook/CreateEditEntryModal/style.ts
  src/routes/safe/components/AddressBook/DeleteEntryModal/index.tsx
  src/routes/safe/components/AddressBook/DeleteEntryModal/style.ts
  src/routes/safe/components/Balances/SendModal/index.tsx
  src/routes/safe/components/Balances/index.tsx
  src/routes/safe/components/Balances/style.ts
  src/routes/safe/components/Layout/style.ts
  src/routes/safe/components/Settings/Advanced/RemoveModuleModal.tsx
  src/routes/safe/components/Settings/Advanced/style.ts
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/style.ts
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/index.tsx
  src/routes/safe/components/Settings/RemoveSafeModal/index.tsx
  src/routes/safe/components/Settings/RemoveSafeModal/style.ts
  src/routes/safe/components/Settings/SpendingLimit/Modal/index.tsx
  src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Create.tsx
  src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/Review.tsx
  src/routes/safe/components/Settings/SpendingLimit/NewLimitModal/index.tsx
  src/routes/safe/components/Settings/SpendingLimit/RemoveLimitModal.tsx
  src/routes/safe/components/Settings/SpendingLimit/style.ts
Labels: Tech-debt 🚧

#2101 Remove loaded safe via URL from the safe list
  src/components/App/index.tsx
  src/components/SafeListSidebar/index.tsx
  src/logic/addressBook/store/middleware/addressBookMiddleware.ts
  src/logic/safe/hooks/useLoadSafe.tsx
  src/logic/safe/store/actions/fetchSafe.ts
  src/logic/safe/store/middleware/safeStorage.ts
  src/logic/safe/store/models/safe.ts
  src/logic/safe/store/reducer/safe.ts
  src/logic/safe/store/selectors/index.ts
  src/utils/constants.ts
Labels: Enhancement ✨

#2119 Replace Loader by component from SRC
  package.json
  src/components/Loader/index.tsx
  src/components/Root/index.tsx
  src/components/ScanQRModal/index.tsx
  src/components/Table/index.tsx
  src/routes/index.tsx
  src/routes/safe/components/Balances/SendModal/index.tsx
  src/routes/safe/components/Settings/index.tsx
  src/routes/safe/components/Transactions/TxList/TxCollapsed.tsx
  src/routes/safe/components/Transactions/TxList/styled.tsx
  yarn.lock
Labels: Tech-debt 🚧

#2159 Assets list - Very long empty page
  src/components/Table/index.tsx
Labels: Bug 🐛, Major

#2160 Enable WalletConnect for xDai chain
  src/config/networks/xdai.ts
Labels: Feature 👑

#2185 Bugfix - Submit button out of screen in Contract Interaction modal
  src/components/Modal/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/style.ts
Labels: Bug 🐛

#2121 Replace Identicon by component from SRC
  src/components/App/ReceiveModal.tsx
  src/components/CopyBtn/copy.svg
  src/components/CopyBtn/index.tsx
  src/components/EtherscanLink/index.tsx
  src/components/EtherscanLink/style.ts
  src/components/Identicon/index.tsx
  src/routes/load/components/OwnerList/index.tsx
  src/routes/load/components/OwnerList/styles.ts
  src/routes/load/components/ReviewInformation/index.tsx
  src/routes/load/components/ReviewInformation/styles.ts
  src/routes/open/components/ReviewInformation/index.tsx
  src/routes/open/components/ReviewInformation/styles.ts
  src/routes/safe/components/AddressBook/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/SendCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/style.ts
  src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/style.ts
  src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendCollectible/style.ts
  src/routes/safe/components/Settings/Advanced/ModulesTable.tsx
  src/routes/safe/components/Settings/Advanced/RemoveModuleModal.tsx
  src/routes/safe/components/Settings/Advanced/style.ts
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/Review/style.ts
  src/routes/safe/components/Settings/ManageOwners/EditOwnerModal/index.tsx
  src/routes/safe/components/Settings/ManageOwners/OwnerAddressTableCell/index.tsx
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/CheckOwner/index.tsx
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/CheckOwner/style.ts
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ManageOwners/RemoveOwnerModal/screens/Review/style.ts
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/style.ts
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/Review/style.ts
  src/routes/safe/components/Settings/ManageOwners/index.tsx
  src/routes/safe/components/Settings/RemoveSafeModal/index.tsx
  src/routes/safe/components/Settings/RemoveSafeModal/style.ts
Labels: Tech-debt 🚧

#2175 Replace DividerLine and Hairline by component from SR
  src/components/Divider/divider.stories.tsx
  src/components/Divider/index.tsx
  src/components/DividerLine/arrow-down.svg
  src/components/DividerLine/index.tsx
  src/routes/safe/components/Apps/components/ConfirmTxModal/ReviewConfirm.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/FormDivisor/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/SendCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewCollectible/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ReviewSendFundsTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
  src/routes/safe/components/Transactions/helpers/EditTxParametersForm/index.tsx
  src/routes/safe/components/Transactions/helpers/EditTxParametersForm/style.ts
Labels: Tech-debt 🚧

#2174 Bugfix - Long values for Amount and Address fields
  src/components/forms/validator.ts
  src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
Labels: Bug 🐛
