Repository gnosis/safe-react, pull requests merged in 2021-06, with the labels that each got.

#2363 Fix crash with Coinbase Wallet after upgrade to latest version
  src/components/AppLayout/Header/components/WalletIcon/icons/icon-coinbase.svg
  src/components/AppLayout/Header/components/WalletIcon/icons/index.ts
  src/logic/wallets/getWeb3.ts
Labels: Bug 🐛, Critical

#2380 Use the same link in the import and export modals
  src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
  src/routes/safe/components/AddressBook/HelpInfo/index.tsx
  src/routes/safe/components/AddressBook/ImportEntryModal/index.tsx
Labels: epic-address-book

#2390 [Address Book v2] Allow empty owner names when loading a safe
  src/components/forms/validator.ts
  src/routes/load/components/DetailsForm/index.tsx
  src/routes/load/components/Layout.tsx
  src/routes/load/components/OwnerList/index.tsx
  src/routes/load/components/ReviewInformation/index.tsx
  src/routes/load/container/Load.tsx
Labels: epic-address-book

#2387 keep safes with no name for the list of safes
  src/logic/safe/store/middleware/safeStorage.ts
  src/logic/safe/store/selectors/index.ts
  src/routes/open/container/Open.tsx
Labels: epic-address-book

#2391 [Address Book v2] Set default order by name
  src/routes/safe/components/AddressBook/index.tsx
Labels: epic-address-book

#2364 Bugfix - Owners table sorting is not working correctly
  src/components/Table/index.tsx
  src/components/Table/sorting.ts
  src/components/Table/types.d.ts
  src/routes/safe/components/Settings/ManageOwners/dataFetcher.ts
Labels: Bug 🐛

#2388 Replace icons and styles on Settings and Address Book
  src/assets/icons/trash.svg
  src/components/AppLayout/Sidebar/SafeHeader/index.tsx
  src/components/ButtonHelper/index.tsx
  src/routes/open/components/SafeOwnersConfirmationsForm/index.tsx
  src/routes/open/components/SafeOwnersConfirmationsForm/style.ts
  src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
  src/routes/safe/components/AddressBook/ImportEntriesModal/index.tsx
  src/routes/safe/components/AddressBook/index.tsx
  src/routes/safe/components/AddressBook/style.ts
  src/routes/safe/components/Settings/Advanced/ModulesTable.tsx
  src/routes/safe/components/Settings/ManageOwners/assets/icons/rename-owner.svg
  src/routes/safe/components/Settings/ManageOwners/assets/icons/replace-owner.svg
  src/routes/safe/components/Settings/ManageOwners/index.tsx
  src/routes/safe/components/Settings/ManageOwners/style.ts
  src/routes/safe/components/Settings/SpendingLimit/LimitsTable/index.tsx
  src/routes/safe/components/Settings/index.tsx
  src/routes/safe/components/Settings/style.ts
Labels: epic-address-book

#2372 [Address Book v2] - Refactor addressBook selectors
  src/logic/addressBook/store/selectors/index.ts
  src/logic/addressBook/utils/__tests__/addressBookUtils.test.ts
  src/logic/addressBook/utils/index.ts
  src/logic/safe/store/selectors/index.ts
  src/routes/load/components/OwnerList/index.tsx
  src/routes/open/components/Layout.tsx
  src/routes/open/components/SafeOwnersConfirmationsForm/index.tsx
  src/routes/safe/components/AddressBook/CreateEditEntryModal/index.tsx
  src/routes/safe/components/AddressBook/EllipsisTransactionDetails/index.tsx
  src/routes/safe/components/AddressBook/ExportEntriesModal/index.tsx
  src/routes/safe/components/AddressBook/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/AddressBookInput/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/Review/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendCollectible/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/SendFunds/index.tsx
  src/routes/safe/components/Settings/ManageOwners/AddOwnerModal/screens/OwnerForm/index.tsx
  src/routes/safe/components/Settings/ManageOwners/ReplaceOwnerModal/screens/OwnerForm/index.tsx
  src/routes/safe/components/Settings/SpendingLimit/FormFields/Beneficiary.tsx
  src/routes/safe/components/Settings/SpendingLimit/InfoDisplay/AddressInfo.tsx
  src/routes/safe/components/Transactions/TxList/OwnerRow.tsx
  src/routes/safe/components/Transactions/TxList/hooks/useKnownAddress.ts
Labels: epic-address-book

#2416 🔥 Fix disappearing safes after migration
  package.json
  src/logic/addressBook/utils/v2-migration.ts
Labels: epic-address-book

#2399 (Fix) Preserve contract name in custom contract interaction flow
  src/routes/safe/components/Balances/SendModal/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/ReviewCustomTx/index.tsx
  src/routes/safe/components/Balances/SendModal/screens/ContractInteraction/SendCustomTx/index.tsx
Labels: epic-address-book

#2431 Bugfix - Warning in console regarding stepIndex variable
  src/routes/opening/index.tsx
Labels: Bug 🐛

#2426 Bugfix - Sentry error
  src/components/AppLayout/Header/components/WalletIcon/icons/icon-squarelink.png
  src/components/AppLayout/Header/components/WalletIcon/icons/index.ts
  src/logic/wallets/getWeb3.ts
Labels: Bug 🐛

#2444 Bugfix - Names are not autocompleted when using known addresses
  src/components/forms/AddressInput/index.tsx
  src/routes/open/components/SafeOwnersConfirmationsForm/index.tsx
Labels: Bug 🐛

#2433 Add hover state to Icons
  package.json
  src/components/AppLayout/Sidebar/SafeHeader/index.tsx
  src/components/ButtonHelper/index.tsx
  src/routes/safe/components/AddressBook/style.ts
  yarn.lock
Labels: Enhancement ✨

#2466 (Bugfix)Spending Limit UI
  src/routes/safe/components/Settings/SpendingLimit/LimitsTable/index.tsx
  src/routes/safe/components/Settings/SpendingLimit/style.ts
Labels: Bug 🐛

#2470 Update templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
Labels: Tech-debt 🚧

#2484 🔥 Fix "Cannot read property'toLowerCase' of undefined" in autocomplete
  src/logic/addressBook/utils/index.ts
  src/logic/addressBook/utils/v2-migration.ts
Labels: Bug 🐛

#2468 [L2] Add Binance Smart Chain config
  .github/workflows/deploy-bsc.yml
  docs/networks.md
  package.json
  src/config/assets/token_bnb.svg
  src/config/networks/bsc.ts
  src/config/networks/index.ts
  src/config/networks/network.d.ts
  src/routes/opening/index.tsx
  src/routes/opening/utils/getSafeAddressFromLogs.ts
  yarn.lock
Labels: epic-l2

#2477 Offer the user to switch/add MetaMask chain
  src/components/AppLayout/Header/components/CircleDot.tsx
  src/components/AppLayout/Header/components/Layout.tsx
  src/components/AppLayout/Header/components/NetworkSelector.tsx
  src/components/AppLayout/Header/components/ProviderDetails/UserDetails.tsx
  src/components/AppLayout/Header/components/ProviderInfo/ProviderAccessible.tsx
  src/components/AppLayout/Header/index.tsx
  src/components/ConnectButton/index.tsx
  src/components/layout/Backdrop/index.tsx
  src/config/index.ts
  src/config/networks/bsc.ts
  src/logic/exceptions/registry.ts
  src/logic/notifications/notificationTypes.ts
  src/logic/wallets/__tests__/network.test.ts
  src/logic/wallets/store/actions/fetchProvider.ts
  src/logic/wallets/utils/network.ts
  src/routes/welcome/components/index.tsx
Labels: epic-l2

#2490 Hide switch button when not MetaMask
  src/components/AppLayout/Header/components/ProviderDetails/UserDetails.tsx
  src/components/AppLayout/Header/index.tsx
  src/logic/wallets/__tests__/network.test.ts
  src/logic/wallets/utils/network.ts
Labels: epic-l2

#2496 Enable apps for BSC
  src/config/networks/bsc.ts
Labels: epic-l2

#2474 [L2] Use MultiSendCallOnly instead of MultiSend contract
  src/logic/contracts/safeContracts.ts
  src/logic/contracts/spendingLimitContracts.ts
  src/logic/safe/transactions/multisend.ts
  src/logic/safe/utils/spendingLimits.ts
  src/logic/safe/utils/upgradeSafe.test.ts
  src/logic/safe/utils/upgradeSafe.ts
Labels: epic-l2

#2471 [L2] Polygon config
  .github/workflows/deploy-polygon.yml
  package.json
  src/config/assets/token_matic.svg
  src/config/networks/index.ts
  src/config/networks/network.d.ts
  src/config/networks/polygon.ts
Labels: Feature 👑, epic-l2

#2506 Text ellipsis for sApp description
  src/routes/safe/components/Apps/components/AppCard/index.tsx
Labels: Bug 🐛
