Repository gnosis/safe-react, pull requests merged in 2021-08, with the labels that each got.

#2615 [Gateway SDK] Post transactions using client-gateway
  src/logic/contracts/safeContracts.ts
  src/logic/safe/store/actions/createTransaction.ts
  src/logic/safe/store/actions/processTransaction.ts
  src/logic/safe/transactions/txHistory.ts
  src/logic/wallets/getWeb3.ts
Labels: Blocked 🤷

#2149 Update Electron to version 13
  .eslintignore
  .github/workflows/release-mainnet-desktop.yml
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .prettierignore
  package.json
  public/auto-updater/index.js
  public/auto-updater/index.ts
  public/electron.ts
  scripts/notarize.js
  scripts/preload.js
  scripts/rescripts/webpack.js
  src/components/AppLayout/MobileNotSupported/index.tsx
  src/components/ConnectButton/index.tsx
  src/components/GlobalErrorBoundary/index.tsx
  src/components/Notifier/index.ts
  src/components/SafeListSidebar/index.tsx
  src/components/Table/index.tsx
  src/logic/contracts/safeContracts.ts
  src/logic/notifications/store/reducer/notifications.ts
  src/logic/safe/store/actions/utils.ts
  src/logic/safe/store/models/types/transaction.ts
  src/logic/safe/store/reducer/safe.ts
  src/logic/safe/transactions/send.ts
  src/logic/safe/transactions/txHistory.ts
  src/logic/safe/utils/safeVersion.ts
  src/logic/safe/utils/upgradeSafe.test.ts
  src/logic/safe/utils/upgradeSafe.ts
  src/routes/safe/components/Apps/communicator.ts
  src/routes/safe/components/Apps/components/AppCard/index.tsx
  src/routes/safe/components/Apps/components/AppFrame.tsx
  src/store/index.ts
  src/test/utils/safeHelper.ts
  src/theme/mui.ts
  tsconfig.electron.json
  tsconfig.json
  yarn.lock
Labels: Dev Tooling 🛠️

#2688 [Hotfix v3.13.1] Create basic migration for addressbook chain id
  src/logic/addressBook/store/selectors/index.ts
Labels: Bug 🐛, Critical
